=== gcross/habit-of-fate-2/data/stories/story.dtd
<!ELEMENT substitute (candidate+)>
<!ATTLIST  substitute placeholder CDATA #REQUIRED>

<!ELEMENT fame (#PCDATA)>

<!ELEMENT candidate EMPTY>
<!ATTLIST  candidate name CDATA #REQUIRED>
<!ATTLIST  candidate gender (male|female|neuter) #REQUIRED>

<!ELEMENT narrative (p+)>
<!ATTLIST  narrative title CDATA #REQUIRED>

<!ELEMENT event (p+,success,danger,averted,failure,shame+)>
<!ATTLIST  event title CDATA #REQUIRED>
<!ATTLIST  event question CDATA #REQUIRED>

<!ELEMENT success (p+)>
<!ATTLIST  success choice CDATA #REQUIRED>
<!ATTLIST  success title CDATA #REQUIRED>

<!ELEMENT danger (p+)>
<!ATTLIST  danger choice CDATA #REQUIRED>
<!ATTLIST  danger title CDATA #REQUIRED>
<!ATTLIST  danger question CDATA #REQUIRED>

<!ELEMENT averted (p+)>
<!ATTLIST  averted choice CDATA #REQUIRED>
<!ATTLIST  averted title CDATA #REQUIRED>

<!ELEMENT failure (p+)>
<!ATTLIST  failure choice CDATA #REQUIRED>
<!ATTLIST  failure title CDATA #REQUIRED>

<!ELEMENT shame (#PCDATA)>

<!ELEMENT branch (p+,choice+)>
<!ATTLIST  branch title CDATA #REQUIRED>
<!ATTLIST  branch question CDATA #REQUIRED>

<!ELEMENT choice (substitute|narrative|event|branch|random|sequence|file)>
<!ATTLIST  choice selection CDATA #REQUIRED>

<!ELEMENT random (narrative|event|branch|random|sequence|file)+>

<!ELEMENT sequence (substitute*,fame*,(narrative|event|branch|random|sequence|file)+)>

<!ELEMENT p (#PCDATA|b)*>
<!ELEMENT  b (#PCDATA)>

<!ELEMENT file EMPTY>
<!ATTLIST  file path CDATA #REQUIRED>

=== gcross/habit-of-fate-2/data/stories/forest.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sequence SYSTEM "story.dtd">
<sequence>
  <substitute placeholder="">
    <candidate name="Andrea" gender="female" />
  </substitute>
  <substitute placeholder="Child">
    <candidate name="Tommy" gender="male" />
  </substitute>
  <substitute placeholder="Plant">
    <candidate name="Illsbane" gender="neuter" />
  </substitute>
  <substitute placeholder="WrongPlant">
    <candidate name="Tigerlamp" gender="neuter" />
  </substitute>
  <fame>With your help, | was able to find a |Plant plant in time to save poor little |Child.</fame>
  <fame>By the grace of You, |Child was saved by medicine made from a precious |Plant found by |.</fame>
  <narrative title="A Healer Enters the Woods">
    <p>
There were times when <b>|</b>, the village healer, cursed himself/herself| for deciding to become a healer, and this was one of them. Little <b>|Child</b> has brain fever, and the only way he/she|Child would survive the night is if he/she| could make a potion with <b>a |Plant</b> plant. Unfortunately, she is out of this herb, and the only way to get more of it is to search the Wicked Forest. He/she| considers telling the family that they would have to be the ones to do this, but his/her| conscience tells him/her| that it is his/her| duty, besides which they might not recognize it and pick the wrong plant. Also the gold helps.
    </p>
    <p>
    He/she| enters the forest.
    </p>
  </narrative>
  <random>
    <narrative title="Wolves Howl">
      <p>
As | continues to search he/she| hears the howling of wolves, which makes him/her| shiver. Thank goodness they seem to be in the distance!
      </p>
    </narrative>
    <event
      title="The Gingerbread House"
      question="Where do You guide |?"
    >
      <p>
| sees a house made out of... gingerbread?  He/she| feels a strange compulsion to approach it.
      </p>
      <success
        choice="Away from the gingerbread house."
        title="Even Gingerbread Cannot Slow The Search"
      >
        <p>
He/she| fights the compulsion, and continues on his/her| search.
        </p>
      </success>
      <danger
        choice="Towards the gingerbread house."
        title="The Gingerbread Compulsion is Too Great"
        question="How do you have | react?"
      >
        <p>
As he/she| gets closer, the door opens and an old woman beckons him/her| in.  “You've arrived just in time!” she says. “Dinner has just finished cooking. Come on in!”
        </p>
      </danger>
      <averted
        choice="He/She| runs away!"
        title="Escaping The Gingerbread House"
      >
        <p>
The smell from the cottage is overwhelming, and shocks | to his/her| senses. He/she| sprints away from the cottage as fast as he/she| can.
        </p>
      </averted>
      <failure
        choice="He/She| enters the house."
        title="Entering The Gingerbread House"
      >
        <p>
Not knowing why he/she| was doing this, | enters the... cottage? The woman leads her to an oven. “Here, look inside.”
        </p>
        <p>
| looks inside the oven and sees... little |Child? he/she| screams, and faints.
        </p>
        <p>
Daylight awakens her. He/she| looks around, but the gingerbread house is nowhere to be found.
        </p>
        <p>
He/she| sobs -- there is no way that he/she| will be able to make it home in time to save |Child now.  All of that gold will be lost!
        </p>
      </failure>
      <shame>You made the sweet smell of gingerbread be just too alluring for |.</shame>
      <shame>You caused |Child to be completely forgotten as | was drawn into a gingerbread house.</shame>
    </event>
    <narrative title="Candle Goes Out">
      <p>
|'s candle goes out; the resulting darkness is oppressive. Fortunately, he/she| had prepared for this. He/she| reached into his/her| pack and drew out flintstone, which he/she| uses to re-light the candle.
      </p>
    </narrative>
    <narrative title="Shadow Stops Moving">
      <p>
| can feel that something is amiss, but he/she| can't figure out what.  He/she| pauses for a moment and looks around. After a moment, he/she| realizes that his/her| shadow didn't stop walking when he/she| did. He/she| backs away
slowly as his/her| shadow gets further and further away from him/her|.  He/she| decides to start searching in a different direction.
      </p>
    </narrative>
    <event
      title="The Mushroom Circle"
      question="Does she see it in time?"
    >
      <p>
A mushroom circle lies just along |'s path, but he/she| is so busy looking for a |Plant plant that he/she| walks straight towards it.
      </p>
      <success
        choice="Yes."
        title="Mushroom Circle Averted"
      >
        <p>
Fortunately, | sees it just before stepping inside. After a moment of letting his/her| heart calm down, he/she| says a prayer of thanks to you and resumes searching in a different direction.
        </p>
      </success>
      <danger
        choice="No."
        title="| Steps Inside"
        question="Does she make it out in time?"
      >
        <p>
Unfortunately, by the time | notices it she was already inside. Desperately, he/she| turns around and starts to run out of it.
        </p>
      </danger>
      <averted
        choice="Yes."
        title="Escaping The Fairy Ring"
      >
        <p>
Miraculously, he/she| makes it out. He/she| continues the search.
        </p>
      </averted>
      <failure
        choice="No."
        title="Traped in the Fairy Circle"
      >
        <p>
Unfortunately, he/she| sees a leprechaun between him/her| and the mushroom border. “Welcome, mortal!” it says to him/her| cheerfully. “I am sure you will have a wonderful time in our land.”
        </p>
        <p>
His/her| time in the fairy world feels like a dream; when it is all over, he/she| can hardly remember what it had been like. He/she| finds himself/herself| standing in the forest in the bright light of day, with mushrooms nowhere to be seen. He/she| runs back to the village, but it is no longer there--at least, as she remembered it. The houses are not in the same place and were larger, the dirt roads are now covered with some black material and have strange shiny creatures on them, and branchless trees are everywhere with black rope strung between them for unknown reasons. He/she| has no idea how much time he/she| had spent away from the world, but she knew that |Child, as well as everyone else he/she| had known and loved, was certainly dead.
        </p>
      </failure>
      <shame>| was teleported by You to a distant realm through the enigmatic magic of the fairies, and there was no way to make it back in time to save |Child.</shame>
    </event>
  </random>
  <branch
    title="Some Help Arrives?"
    question="Who is it?"
  >
    <p>
Finally, just when all hope is lost, a creature arrives to help |.
    </p>
    <choice selection="A cat.">
      <event
        title="Chance Encounter with a Cat"
        question="What color is the cat?"
      >
        <p>
| hears a meow. He/she| looks to the source, and sees a forest cat. It is hard to see the color of the cat, which is a problem because it is the best way of being able to tell whether the cat is evil or not.
        </p>
        <p>
The cat beckons to him/her| and starts walking. Should he/she| follow the cat?  As trepidatious as he/she| is feeling about the situation, he/she| does really need to get the herb as soon as he/she| can, and this is the best lead he/she| has had all night. He/she| decides to roll the dice and follow the cat.
        </p>
        <success
          choice="Green."
          title="Following the Cat"
        >
          <p>
He/she| follows the cat for some time, and eventually it stops. It picks something up and brings it to him/her|. Excitedly, she bends down to look at it.
          </p>
          <p>
It is a mouse.
          </p>
          <p>
He/she| growls and tosses the mouse to the side. He/she| starts to walk away when he/she| realizes that the cat is sitting right next to a |Plant plant. A beam of moonlight reveals that the cat has green fur.
          </p>
          <p>
Well, cats are cats, even the good ones.
          </p>
          <p>
He/she| walks over and picks the plant, and then scratches the cat. “Good kitty!” he/she| says. It purrs.
          </p>
          <p>
He/she| starts to journey home.
          </p>
        </success>
        <danger
          choice="Blue."
          title="Following The Cat"
          question="Is she hurt?"
        >
          <p>
| chases after the cat, barely able to keep up.  It is because of this that he/she| does not notice that she is stepping into a pit.
          </p>
        </danger>
        <averted
          choice="No."
          title="Missed Getting Hurt"
        >
          <p>
| follows into the pit but somehow avoids getting any broken bones.  He/she| looks up in time to see the cat, its blue fur finally shown clearly in a beam of moonlight, flash him/her| a cheshire grin and vanish.
          </p>
          <p>
| grumbles at the existence of mischievous malevolent cats, but at least he/she| notices a |Plant herb at the bottom so she can start heading home.
          </p>
        </averted>
        <failure
          choice="Yes."
          title="Can't Get Up"
        >
          <p>
Too late he/she| realizes that he/she| is stepping into a pit. Unable to catch himself/herself| in time, he/she| falls into the put, breaking a leg. The cat looks down into the pit, its fur clearly revealed to be blue in the moonlight, and flashes him/her| a cheshire grin, after which it vanishes.   | growls in anger and then faints in pain. |Child will not be getting the medicine that he/she|Child desperately needs tonight...
          </p>
        </failure>
        <shame>You caused | to act against their better judgement in following a forest cat at night without knowing its color.</shame>
